apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jfrog-repo
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  jfrog-repo-job:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: jfrog-actions-workflow-promote-file
        uses: cloudbees-io/jfrog-artifactory-promote-image@v1
        with:
          url: ${{ vars.JFROG_URL }}
          username: ${{ vars.JFROG_ACTIONS_USERNAME }}
          password: ${{ secrets.JFROG_ACTIONS_PASSWORD }}
          source-repository-name: jfrog-xray-test
          target-repository-name: jfrog-test-docker-target-repo
          source-image-name: test-image
          source-tag: latest
          copy: "true"
